### ISSUE TITLE
Crash in Block Tool

### ISSUE THREAD

**Issue by Javantea** [kirjavascript/TetrisGYM#18]
Set up block tool. Press select + start + a + b.

Expected: go back to main menu

Actual: glitch artifacts and the tool malfunctions or go back to main menu depending on how you press or some other unknown. The game still allows you to go back to the main menu by pressing again.

Video: https://youtu.be/SVkcF0TVCXQ

**Comment by kirjavascript** [comment]
Hi! Thanks for reporting this!

I think it's because it tries to save and load at the same time and tries to display a sprite that doesnt exist so it throws garbage into the OAM.

Thankfully it's mostly harmless and can be avoided by using the correct order a + b + select + start instead

It just needs a small tweak to fix and will be included in future revisions.

**Comment by Javantea** [comment]
That sounds reasonable. I'm happy to test the fix when it's ready. I'm surprised that order matters in that sequence. Thanks.
