### ISSUE TITLE
PAL mode detection is unreliable

### ISSUE THREAD

**Issue by Hyphen-ated** [kirjavascript/TetrisGYM#3]
I'm playing on an original NTSC NES with an Everdrive N8.
About 90% of the time when I launch the game, it correctly starts with PAL mode off.
About 10% of the time, it starts with PAL mode on. 

The first time it happened it felt like I was going crazy -- "why is DAS moving the pieces so fast all of a sudden??"
The second time it happened I thought to myself "well, this romhack is just broken so I guess I'll delete it", but luckily I realized the cause before doing that.

If the detection can't be made reliable, maybe it would be better to have two separate versions of the rom?

**Comment by kirjavascript** [comment]
A few things to consider here.

The NES console is deterministic. That is, given the same game and same hardware and IO inputs, the same thing will happen every time. Therefore it should *always* show the same version each time, otherwise there must be some issue with the hardware, as in a loose connection or similar causing ROM corruption of some kind.

That said, region detection is tricky business and my be prone to some weird timing issue that I'm not aware of?

The code to do this is here if you want to look: https://github.com/kirjavascript/TetrisGYM/blob/master/main.asm#L596

Two separate versions is a possibility, however this is the first time this has cropped up after it has been extensively tested with no reports of this happening elsewhere. I suspect the problem is due to some hardware error rather than the game itself and would want to confirm this before taking further action. As a workaround for now you can just ensure the region switch is set correctly.

**Comment by kirjavascript** [comment]
try this!

[tetris.bps.gz](https://github.com/kirjavascript/TetrisGYM/files/6465693/tetris.bps.gz)

(I had to gzip the file because github doesnt support bps in comments)

**Comment by Hyphen-ated** [comment]
I powercycled and loaded the rom 40 times and didn't experience the problem. Before filing this issue I made two attempts to reproduce it, and it happened after ~6 and ~10 tries

Thanks!

**Comment by kirjavascript** [comment]
so after some testing in emulators and on hardware, this code (from the link) doesnt seem to work correctly and always defaults to NTSC

seems another approach is needed

**Comment by kirjavascript** [comment]
@Hyphen-ated here's a newer fixed version, could you also test this?
[tetris.bps.gz](https://github.com/kirjavascript/TetrisGYM/files/6659238/tetris.bps.gz)

**Comment by Hyphen-ated** [comment]
I tried 40 times and it worked each time

**Comment by kirjavascript** [comment]
cheers
